### ISSUE TITLE
Deprecated Atom APIs will be removed June 1st

### ISSUE THREAD

**Issue by benogle** [manuclementz/atom-faker#3]
Atom will no longer load this package after June 1st without changes. There is one deprecation on the latest version (`0.2.0`) of this package:

1. atom.workspaceView is no longer available. In most cases you will not need the view. See the Workspace docs for alternatives: https://atom.io/docs/api/latest/Workspace. If you do need the view, please use `atom.views.getView(atom.workspace)`, which returns an HTMLElement.

Visit https://gist.github.com/benogle/6d09e295c84b717ef9b4 and search for your package name to see up-to-date deprecations.

If this package has been replaced by another package or functionality in core, please reply with this information.

See https://github.com/atom/atom/issues/6867 for more info. Thanks!

**Comment by dsandstrom** [comment]
@benogle I tried to fix this, but @manuclementz is using interpolation when adding commands

```coffee
...
for cls of availableCommands
  for cmd of availableCommands[cls]
    @subscriptions.add atom.commands.add "atom-workspace",
      "atom-faker:(#{cls})-#{cmd}": => @createCmd(cls, cmd)
...
```
This gives me an error: "unexpected :".  Is this a bug or am I doing it wrong?

**Comment by benogle** [comment]
This should work:

```coffee
module.exports =
  activate: (state) ->
    for cls of availableCommands
      for cmd of availableCommands[cls]
        @subscriptions.add(createCmd(cls, cmd))

createCmd = (cls, cmd) ->
  atom.commands.add 'atom-workspace', "atom-faker:(#{cls})-#{cmd}", ->
    editor = atom.workspace.getActiveEditor()
    return unless editor?
    fn = availableCommands[cls][cmd]
    editor.insertText faker[cls][fn]()
```

**Comment by benogle** [comment]
Remember to convert `getActiveEditor` to `getActiveTextEditor`
